apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: discovery-server
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: registry.dop.clsaa.com/dop/discovery-server:<BUILD_TAG>
          resources:
            requests:
              memory: 384Mi
              cpu: 250m
            limits:
              memory: 384Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 8888
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: discovery-server-mapping
      prefix: /
      service: discovery-server.dop
      host: discovery.dop.clsaa.com
  namespace: dop
  labels:
    app: discovery-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: discovery-server
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: discovery-server
#  namespace: dop
#spec:
#  rules:
#  - host: discovery.dop.clsaa.com
#    http:
#      paths:
#      - backend:
#          serviceName: discovery-server
#          servicePort: 8761
