apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-server
  namespace: dop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          image: registry.cn-hangzhou.aliyuncs.com/softeng-dop/user-server
          ports:
            - containerPort: 13100
---
apiVersion: v1
kind: Service
metadata:
  name: user-server
  namespace: dop
  labels:
    app: user-server
spec:
  ports:
    - port: 13100
      protocol: TCP
      targetPort: 13100
  selector:
    app: user-server
