apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pipeline-server
  namespace: dop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pipeline-server
    spec:
      containers:
        - name: pipeline-server
          imagePullPolicy: Always
          image: 121.42.13.243:30000/dop/pipeline-server:<BUILD_TAG>
          resources:
            requests:
              memory: 384Mi
              cpu: 250m
            limits:
              memory: 384Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 13600
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-server
  namespace: dop
  labels:
    app: pipeline-server
spec:
  ports:
    - port: 13600
      protocol: TCP
      targetPort: 13600
  selector:
    app: pipeline-server
