apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-server
  namespace: dop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
        - name: message-server
          imagePullPolicy: Always
          image: registry.dop.clsaa.com/dop/message-server:<BUILD_TAG>
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 13400
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: message-server
  namespace: dop
  labels:
    app: message-server
spec:
  ports:
    - port: 13400
      protocol: TCP
      targetPort: 13400
  selector:
    app: message-server
